# =============================================================================
# Docker Compose Override for Development Environment
# =============================================================================
# This file provides development-specific overrides for docker-compose.yml
# It enables hot reloading, debugging features, and development-friendly settings
# =============================================================================

version: '3.8'

services:
  db:
    # Development database configuration
    environment:
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev_password_123
      - POSTGRES_DB=edupro_dev_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts with local PostgreSQL
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d:ro
    command: >
      postgres 
      -c log_statement=all 
      -c log_destination=stderr 
      -c log_min_duration_statement=0
      -c shared_preload_libraries=pg_stat_statements

  app:
    # Development app configuration
    build:
      target: development  # Use development stage if multi-stage Dockerfile
    environment:
      - NODE_ENV=development
      - DEBUG=*
      - VERBOSE_LOGGING=true
      - HOT_RELOAD=true
      - DATABASE_URL=postgresql://dev_admin:dev_password_123@db:5432/edupro_dev_db?schema=public
      - JWT_SECRET=development-jwt-secret-key-not-for-production-use-only
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-nextauth-secret-not-for-production
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - MAX_FILE_SIZE=52428800  # 50MB for development
      - RATE_LIMIT_MAX_REQUESTS=1000  # Higher limits for development
      - RATE_LIMIT_WINDOW_MS=60000    # 1 minute window
      - LOG_LEVEL=debug
      - ANTIVIRUS_ENABLED=false
    volumes:
      # Enable hot reloading by mounting source code
      - .:/app:cached
      - /app/node_modules
      - /app/.next
      # Development-specific volumes
      - dev_uploads:/app/public/uploads:rw
      - ./logs:/app/logs:rw
      - ./dev-tools:/app/dev-tools:rw
    ports:
      - "3000:3000"  # Expose app directly for development
      - "9229:9229"  # Node.js debugging port
    command: >
      sh -c "
        echo 'Starting development server...' &&
        npm run dev
      "
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    # Development nginx configuration
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - dev_uploads:/app/public/uploads:ro
    ports:
      - "8080:80"  # Different port for development
    environment:
      - NGINX_LOG_LEVEL=debug
    depends_on:
      app:
        condition: service_started  # Less strict dependency for development

  # Development-specific services
  redis:
    image: redis:7-alpine
    container_name: edupro-suite-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - edupro-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  mailhog:
    image: mailhog/mailhog:latest
    container_name: edupro-suite-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - edupro-network

  # Development database admin tool
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: edupro-suite-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@edupro.dev
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - edupro-network
    depends_on:
      - db

volumes:
  postgres_dev_data:
    driver: local
  dev_uploads:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local

# Development-specific network configuration
networks:
  edupro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16  # Different subnet for development
