version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: edupro-suite-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strong_password_123
      - POSTGRES_DB=edupro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edupro-network
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: edupro-suite-app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - edupro-network
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DATABASE_URL=postgresql://admin:strong_password_123@db:5432/edupro_db?schema=public
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NEXTAUTH_URL=https://abrar.ailearnersbd.com
    command: sh -c "node server.js"

  nginx:
    image: nginx:alpine
    container_name: edupro-suite-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - edupro-network

volumes:
  postgres_data:

networks:
  edupro-network:
    driver: bridge
